name: Test build, publish on release

on: [ push, pull_request, release ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: (1/4) Checkout the repository
        uses: actions/checkout@v4

      - name: (2/4) Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: (3/4) Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: (4/4) Run tests with sbt
        shell: bash
        run: sbt -v +test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') # only run on releases
    steps:
      - name: (1/4) Checkout the repository
        uses: actions/checkout@v4

      - name: (2/4) Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: (3/4) Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: (4/4) Publish the library
        run: sbt publish